Basic mockup
ember-poland/ember-interface pull request #2
Opened 2017-06-22 19:33 UTC by Exelord

Here is a basic mockup of projects list with ember paper and translations :)
After the merge, we should focus on implementing that feature.

![screen shot 2017-06-22 at 21 33 10](https://user-images.githubusercontent.com/1469375/27452306-688c5196-5792-11e7-89e2-a064787ca004.png)

2017-06-22 20:08 UTC, PoslinskiNet commented on app/formats.js
> +    EUR: {
Hmm?

2017-06-22 20:09 UTC, PoslinskiNet requested changes
Remove redundant currency format config.

2017-06-22 20:11 UTC, Exelord commented on app/formats.js
> +    EUR: {
Generated by default ;)

2017-06-25 14:16 UTC, PoslinskiNet approved these changes

2017-06-25 15:31 UTC, merged